// app/layout.js
import "./globals.css";
import { Montserrat } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import LayoutWrapper from "./LayoutWrapper";
import AuthmainLayOut from "./MainLayout";




const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} font-sans`}>
     
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <LayoutWrapper>
              <AuthmainLayOut>
    {children}
              </AuthmainLayOut>
          
              </LayoutWrapper>
          </ThemeProvider>
        
      </body>
    </html>
  );
}
